/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.awt.Color;
import java.util.regex.PatternSyntaxException;

/**
 *
 * @author leont
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        matchBtn = new javax.swing.JButton();
        regexTxt = new javax.swing.JTextField();
        textPane = new javax.swing.JScrollPane();
        textTxt = new javax.swing.JTextArea();
        regexLbl = new javax.swing.JLabel();
        inputLbl = new javax.swing.JLabel();
        resultLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("String Checker");

        mainPanel.setLayout(new java.awt.GridBagLayout());

        matchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        matchBtn.setText("MATCH");
        matchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matchBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 5, 10);
        mainPanel.add(matchBtn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 3, 11);
        mainPanel.add(regexTxt, gridBagConstraints);

        textTxt.setColumns(20);
        textTxt.setLineWrap(true);
        textTxt.setRows(5);
        textTxt.setWrapStyleWord(true);
        textPane.setViewportView(textTxt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 11);
        mainPanel.add(textPane, gridBagConstraints);

        regexLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regexLbl.setText("Regex pattern");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 3, 5);
        mainPanel.add(regexLbl, gridBagConstraints);

        inputLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputLbl.setText("Input text");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        mainPanel.add(inputLbl, gridBagConstraints);

        resultLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resultLbl.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        mainPanel.add(resultLbl, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matchBtnMouseClicked
        try{
            if (Controller.isMatch(regexTxt.getText(), textTxt.getText())){
                resultLbl.setForeground(Color.green);
                resultLbl.setText("OK");
            }
            else{
                resultLbl.setForeground(Color.red);
                resultLbl.setText("NG");
            }
        }
        catch (PatternSyntaxException e){
            resultLbl.setForeground(Color.red);
            resultLbl.setText("Wrong regex format");
        }
    }//GEN-LAST:event_matchBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inputLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton matchBtn;
    private javax.swing.JLabel regexLbl;
    private javax.swing.JTextField regexTxt;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JScrollPane textPane;
    private javax.swing.JTextArea textTxt;
    // End of variables declaration//GEN-END:variables
}
